//
//  SEEnvironmentalBenefits.swift
//  
//
//  Created by Andre Albach on 05.04.23.
//

import Foundation

/// Environmental benefits
public struct SEEnvironmentalBenefits: Codable {
    /// Equivalent planting of new trees for reducing CO2 levels
    public let treesPlanted: Double
    /// Number of light bulbs that could have been powered by the site for a whole day
    public let lightBulbs: Double
    /// Quantity of CO2 emissions that would have been generated by an equivalent fossil fuel system
    public let gasEmissionSaved: SESavedGasEmission
}

extension SEEnvironmentalBenefits {
    /// Saved gas emissions
    public struct SESavedGasEmission: Codable {
        /// The unit of the values
        public let units: String
        /// CO2 saved
        public let co2: Double
        /// SO2 saved
        public let so2: Double
        /// NOX saved
        public let nox: Double
    }
}
