//
//  EnvironmentalBenefits.swift
//  
//
//  Created by Andre Albach on 05.04.23.
//

import Foundation

/// Environmental benefits
public struct EnvironmentalBenefits: Codable {
    /// Equivalent planting of new trees for reducing CO2 levels
    public let treesPlanted: Double
    /// Number of light bulbs that could have been powered by the site for a whole day
    public let lightBulbs: Double
    /// Quantity of CO2 emissions that would have been generated by an equivalent fossil fuel system
    public let gasEmissionSaved: SavedGasEmission
}


extension EnvironmentalBenefits {
    /// Saved gas emissions
    public struct SavedGasEmission: Codable {
        public let units: String
        public let co2: Double
        public let so2: Double
        public let nox: Double
    }
}
